# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8J-FZAxjZqMOkuUYOVXZPvUK4TjkwDq
"""

!pip install streamlit
!pip install pycountry

import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import streamlit as st
import re
import pycountry
import numpy as np

#Page Setup
st.set_page_config(layout="wide")
st.title("Climate Change Policy Bias over time across SADC")

#Load data
drive.mount('/content/drive')
df = pd.read_excel("/content/drive/MyDrive/MIT 808 Byte Squad/Colab/Streamlit Deployment/Overall Model Results.xlsx") # need a point that can read the xlsx file to a dataframe, append the new results, and write back to xslx file before showing results
dfwCntry = pd.read_excel("/content/drive/MyDrive/MIT 808 Byte Squad/Colab/Streamlit Deployment/Overall Model Results w Country.xlsx")

df.columns = df.columns.str.strip()
dfwCntry.columns = dfwCntry.columns.str.strip()

#Filters
st.sidebar.header("Filters")

models = st.sidebar.multiselect(
    "Model Type",
    dfwCntry["Model Type"].dropna().unique(),
    default=dfwCntry["Model Type"].dropna().unique()
)

categories = st.sidebar.multiselect(
    "Category",
    dfwCntry["category"].dropna().unique(),
    default=dfwCntry["category"].dropna().unique()
)

source_types = st.sidebar.multiselect(
    "Source Type",
    dfwCntry["source_type"].dropna().unique(),
    default=dfwCntry["source_type"].dropna().unique()
)

countries = st.sidebar.multiselect(
    "Country",
    dfwCntry["Country"].dropna().unique(),
    default=dfwCntry["Country"].dropna().unique()
)

df_filtered = dfwCntry[
    (dfwCntry["Model Type"].isin(models)) &
    (dfwCntry["category"].isin(categories)) &
    (dfwCntry["source_type"].isin(source_types)) &
    (dfwCntry["Country"].isin(countries))
]

col1,col2,col3, col4 = st.columns(4)
col1.metric("Total Records", len(df_filtered))
col2.metric("Categories", df_filtered["category"].nunique())
col3.metric("Countries", df_filtered["Country"].nunique())
col4.metric("Models", df_filtered["Model Type"].nunique())

st.header("Score distribution by Model")

fig, ax = plt.subplots()
sns.boxplot(data=df_filtered, x="Model Type", y="Score", ax=ax)
ax.set_title("Distribution of Scores by Model Type")
ax.set_xlabel("Model Type")
ax.set_ylabel("Score")
st.pyplot(fig)

st.header("Category Distribution by Source")

fig, ax = plt.subplots()
sns.countplot(hue='source_type', y='category', data=df_filtered, ax=ax)
ax.set_title('Category Distribution by Source Type')
ax.set_xlabel('Count')
ax.set_ylabel('category')
st.pyplot(fig)

st.header("Score Distribution")

fig3, ax = plt.subplots()
sns.histplot(df_filtered['Score'], bins=20, kde=True, ax=ax)
ax.set_title('Distribution of Scores')
ax.set_xlabel('Score')
ax.set_ylabel('Frequency')
st.pyplot(fig3)

#5
st.header("Average Score by Category")

avg_scores = df_filtered.groupby('category')['Score'].mean().sort_values()

fig4, ax = plt.subplots()
avg_scores.plot(kind='barh', ax=ax)
st.pyplot(fig4)

#6
st.header("Category vs Model (Average Score)")

pivot = df_filtered.pivot_table(
    index='category',
    columns='Model Type',
    values='Score',
    aggfunc='mean'
)

fig = px.imshow(
    pivot,
    text_auto=True,
    aspect="auto",
    title="Category vs Model (Average Score)"
)

st.plotly_chart(fig, use_container_width=True)

st.header("Top Countries v Category")

if "Country" in df_filtered.columns:
    top_n = st.slider("Top N Countries", 5, 20, 10)
    top = df_filtered['Country'].value_counts().head(top_n).index

    df_top = dfwCntry[dfwCntry["Country"].isin(top)]
    pivot = pd.crosstab(df_top["Country"], df_top["category"])
    fig, ax = plt.subplots(figsize=(10, 6))
    pivot.plot(kind="bar",
               stacked=True,
               ax=ax)
    plt.xticks(rotation=45)
    st.pyplot(fig)

st.header("Country vs Category (Proportion)")

if "Country" in df_filtered.columns:
    pivot_norm = pivot.div(pivot.sum(axis=1), axis=0)

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(
        pivot_norm,
        annot=True,
        cmap="coolwarm",
        ax=ax
    )
    st.pyplot(fig)

st.header("Policy-Level Bias Profile")

policy = st.selectbox("Select Policy", df["filename"].dropna().unique())

policy_df = df[df["filename"] == policy]

if policy_df.empty:
    st.warning("No data available for the selected policy.")
else:
  category_scores = (
      policy_df.groupby("category")["Score"]
      .mean()
      .reset_index()
  )

  categories_list = category_scores["category"].tolist()
  values = category_scores["Score"].tolist()

  values+= values[:1]
  angles = np.linspace(
      0,
      2 * np.pi,
      len(categories_list),
      endpoint=False
  ).tolist()
  angles += angles[:1]

  fig, ax = plt.subplots(
      figsize=(7,7),
      subplot_kw=dict(polar=True)
  )
  ax.plot(
      angles,
      values,
      linewidth=2
  )
  ax.fill(
      angles,
      values,
      alpha=0.25
  )
  ax.set_xticks(angles[:-1])
  ax.set_xticklabels(categories_list)
  ax.set_ylim(0,5)

  st.pyplot(fig)

st.header("Bias Category Trends Over Time")

df["Year"] = df["filename"].astype(str).str.extract(r'(\d{4})')
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
df_time = df.dropna(subset=["Year"])

heatmap_data = df_time.pivot_table(
    index="category",
    columns="Year",
    values="Score",
    aggfunc="mean"
)

fig, ax = plt.subplots(figsize=(12,6))
sns.heatmap(
    heatmap_data,
    annot=True,
    cmap="YlOrRd",
    linewidths=0.5,
    fmt=".2f",
    ax=ax
)
ax.set_title(
    "Bias Category Trends Over Time",
    fontsize=14
)
ax.set_xlabel("Policy Year")
ax.set_ylabel("Bias Category")
st.pyplot(fig)


#!streamlit run /content/drive/MyDrive/MIT 808 Byte Squad/Colab/Streamlit Deployment/app.ipynb &>/content/drive/MyDrive/MIT 808 Byte Squad/Colab/Streamlit Deployment/logs.txt &